### ISSUE TITLE
loading bignum in utop fails

### ISSUE THREAD

**Issue by yminsky** [janestreet/bignum#1]
for reasons that are not obvious to me.  This errors out:

```
utop # #require "bignum";;
Error: Reference to undefined global `Big_int'
```

Weirdly, this then works:

```
utop # open Bignum.Std;;
```

But this then fails

```
utop # Bignum.of_int;;
Error: Reference to undefined global `Bignum'
```

I have no idea what's going on.

**Comment by ghost** [comment]
The inline unit tests are using the num library and it was missing from the dependencies.
