### ISSUE TITLE
Bignum doesn't build properly (missed dependency on big_int?)

### ISSUE THREAD

**Issue by yminsky** [janestreet/bignum#3]
Something is wrong with the bignum package.  I tried to build this code:

```
open Core.Std
open Bignum.Std

let () = printf "%d\n" (Bigint.to_int (Bigint.of_int 3))
```

When I run the build, I get this, which indicates a missed
dependency on Big_int.  Also, maybe we should change the upstream
package to move the Big_int dependency to the tests alone.

```
corebuild w.native -pkg bignum
ocamlfind ocamlopt -linkpkg -g -thread -syntax camlp4o -package bignum -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core w.cmx -o w.native
+ ocamlfind ocamlopt -linkpkg -g -thread -syntax camlp4o -package bignum -package bin_prot.syntax -package sexplib.syntax,comparelib.syntax,fieldslib.syntax,variantslib.syntax -package core w.cmx -o w.native
File "_none_", line 1:
Error: No implementations provided for the following modules:
     Big_int referenced from /Users/yminsky/.opam/system/lib/bignum/bignum.cmxa(Bignum)
Command exited with code 2.
```

**Comment by ghost** [comment]
It's already fixed in the git repo, we'll do a minor release soon.

> Also, maybe we should change the upstream package to move the Big_int dependency to the tests alone.

Yeah we can probably do that. Currently it's the inline tests/benchmarks that use Big_int, but hopefully all they need is the public API.

**Comment by ghost** [comment]
ocaml/opam-repository#3892
