### ISSUE TITLE
Bignum 113.33.00 from opam doesn't copy zarith_1_4.cmi

### ISSUE THREAD

**Issue by Pyramiden** [janestreet/bignum#4]
I was trying to use ocaml 4.04 + bignum from the official opam repository which provides bignum 113.33.00 (for ocaml >= 4.02.3) and 113.33.03 (for ocaml = 4.02.3).
Everything works great with ocaml 4.02.3 (and therefore bignum 113.33.03) but I figured out that bignum 113.33.00 doesn't copy the interface zarith_1_4.cmi/mli and I had to add it by myself.

**Comment by ghost** [comment]
That's wrong indeed, I thought I fixed this issue already. I'll have another look

**Comment by hhugo** [comment]
@diml, can you comment on this ?

**Comment by ghost** [comment]
113.33.xx packages are using an oasis based build systems. I can't remember what they are doing. I'm closing this as these packages are quite old.
